CREATE SCHEMA OTC_MARKET_ANALYSIS;

CREATE  TABLE OTC_MARKET_ANALYSIS.DIM_DATE ( 
	DATE_ID              integer NOT NULL   ,
	YEAR_NUMBER          integer    ,
	MONTH_NUMBER         integer    ,
	QUARTER_NUMBER       integer    ,
	DAY_NUMBER           integer    ,
	DAY_NAME             varchar(15)    ,
	IS_HOLIDAY           boolean    ,
	HOUR_NUMBER          integer    ,
	MONTH_NAME           varchar(20)    ,
	WEEK_OF_MONTH        integer    ,
	WEEK_OF_YEAR         integer    ,
	CONSTRAINT PK_DIM_DATE PRIMARY KEY ( DATE_ID )
 );

CREATE  TABLE OTC_MARKET_ANALYSIS.DIM_GICS ( 
	GICS_CODE            integer NOT NULL   ,
	SECTOR_CODE          integer    ,
	SECTOR_NAME          varchar(50)    ,
	INDUSTRY_GROUP_CODE  integer    ,
	INDUSTRY_GROUP_NAME  varchar(100)    ,
	INDUSTRY_CODE        integer    ,
	INDUSTRY_NAME        varchar(100)    ,
	SUB_INDUSTRY_CODE    integer    ,
	SUB_INDUSTRY_NAME    varchar(100)    ,
	STATUS               integer    ,
	CONSTRAINT PK_DIM_GICS PRIMARY KEY ( GICS_CODE )
 );

CREATE  TABLE OTC_MARKET_ANALYSIS.DIM_OTC_TIER ( 
	OTC_TIER_ID          integer NOT NULL   ,
	OTC_TIER_NAME        varchar(100)    ,
	DAD_PAL_SPONSOR      varchar(75)    ,
	CONSTRAINT PK_DIM_OTC_TIER PRIMARY KEY ( OTC_TIER_ID )
 );

CREATE  TABLE OTC_MARKET_ANALYSIS.DIM_SECURITY ( 
	SECURITY_ID          integer NOT NULL   ,
	COMPANY_ID           integer    ,
	TRADING_SYMBOL       char(10)    ,
	CUSIP_NUMBER         char(9)    ,
	SECURITY_NAME        varchar(50)    ,
	SECURITY_TYPE        varchar(75)    ,
	SECURITY_CLASS       char(1)    ,
	SECURITY_STATUS      varchar(20)    ,
	FINRA_ISSUER_IDENTIFIER varchar(20)    ,
	SECURITY_DESCRIPTION varchar(255)    ,
	COUNTRY              char(30)    ,
	STATE                char(25)    ,
	COMPANY_NAME         varchar(100)    ,
	CONSTRAINT PK_DIM_SECURITY PRIMARY KEY ( SECURITY_ID )
 );

CREATE  TABLE OTC_MARKET_ANALYSIS.DIM_SOURCE ( 
	SOURCE_ID            integer NOT NULL   ,
	SOURCE_NAME          varchar(100)    ,
	CONSTRAINT PK_DIM_SOURCE PRIMARY KEY ( SOURCE_ID )
 );

CREATE  TABLE OTC_MARKET_ANALYSIS.DIM_TRADING_VENUE ( 
	TRADING_VENUE_ID     integer NOT NULL   ,
	TRADING_VENUE_NAME   varchar(100)    ,
	CONSTRAINT PK_DIM_TRADING_VENUE PRIMARY KEY ( TRADING_VENUE_ID )
 );

CREATE  TABLE OTC_MARKET_ANALYSIS.FACT_OTC_TRANSACTIONS ( 
	FACTS_ID             integer NOT NULL   ,
	CLOSING_INSIDE_BID   number(11,5)    ,
	CLOSING_INSIDE_ASK   number(11,5)    ,
	CLOSING_MID_PRICE    number(11,5)    ,
	PRICE_OPEN           number(11,5)    ,
	PRICE_HIGH           number(11,5)    ,
	PRICE_LOW            number(11,5)    ,
	PRICE_LAST           number(11,5)    ,
	PREVIOUS_CLOSE_PRICE number(11,5)    ,
	SHARE_VOLUME         integer    ,
	DOLLAR_VOLUME        number(30,20)    ,
	TRADE_COUNT          integer    ,
	OTC_LINK_SHARE_VOLUME integer    ,
	OTC_LINK_DOLLAR_VOLUME number(30,20)    ,
	OTC_LINK_TRADE_COUNT integer    ,
	REG_SHO_STATUS_FLAG  char(1)    ,
	RULE_3210_STATUS_FLAG char(1)    ,
	SHORT_INTEREST_SHARES integer    ,
	NUMBER_OF_MARKET_MAKERS integer    ,
	BONA_FIDE_CONTINOUS  integer    ,
	CLOSING_BEST_BID     number(11,5)    ,
	CLOSING_BEST_ASK     number(11,5)    ,
	TOTAL_SHARES_OUTSTANDING number(16,1)    ,
	CLOSING_SPREAD_INSIDE number(11,5)    ,
	CLOSING_SPREAD_BEST  number(11,5)    ,
	PIVOT_POINT          number(11,5)    ,
	CAVEAT_EMPTOR_FLAG   char(1)    ,
	TRADING_VENUE_ID     integer NOT NULL   ,
	SOURCE_ID            integer NOT NULL   ,
	OTC_TIER_ID          integer NOT NULL   ,
	SECURITY_ID          integer NOT NULL   ,
	GICS_ID              integer NOT NULL   ,
	CLOSING_INSIDE_BID_DATE date NOT NULL   ,
	CLOSING_INSIDE_ASK_DATE date NOT NULL   ,
	PREVIOUS_CLOSE_DATE  date NOT NULL   ,
	SHORT_INTEREST_DATE  date NOT NULL   ,
	CLOSING_BEST_BID_DATE date NOT NULL   ,
	CLOSING_BEST_ASK_DATE date NOT NULL   ,
	TOTAL_SHARES_OUTSTANDING_DATE date NOT NULL   ,
	CONSTRAINT PK_FACT_OTC_TRANSACTIONS PRIMARY KEY ( FACTS_ID )
 );

ALTER TABLE OTC_MARKET_ANALYSIS.FACT_OTC_TRANSACTIONS ADD CONSTRAINT FK_FACT_OTC_TRANSACTIONS_DIM_SECURITY FOREIGN KEY ( SECURITY_ID ) REFERENCES OTC_MARKET_ANALYSIS.DIM_SECURITY( SECURITY_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE OTC_MARKET_ANALYSIS.FACT_OTC_TRANSACTIONS ADD CONSTRAINT FK_FACT_OTC_TRANSACTIONS_DIM_OTC_TIER FOREIGN KEY ( OTC_TIER_ID ) REFERENCES OTC_MARKET_ANALYSIS.DIM_OTC_TIER( OTC_TIER_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE OTC_MARKET_ANALYSIS.FACT_OTC_TRANSACTIONS ADD CONSTRAINT FK_FACT_OTC_TRANSACTIONS_DIM_SOURCE FOREIGN KEY ( SOURCE_ID ) REFERENCES OTC_MARKET_ANALYSIS.DIM_SOURCE( SOURCE_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE OTC_MARKET_ANALYSIS.FACT_OTC_TRANSACTIONS ADD CONSTRAINT FK_FACT_OTC_TRANSACTIONS_DIM_GICS FOREIGN KEY ( GICS_ID ) REFERENCES OTC_MARKET_ANALYSIS.DIM_GICS( GICS_CODE ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE OTC_MARKET_ANALYSIS.FACT_OTC_TRANSACTIONS ADD CONSTRAINT FK_FACT_OTC_TRANSACTIONS_DIM_TRADING_VENUE FOREIGN KEY ( TRADING_VENUE_ID ) REFERENCES OTC_MARKET_ANALYSIS.DIM_TRADING_VENUE( TRADING_VENUE_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE OTC_MARKET_ANALYSIS.FACT_OTC_TRANSACTIONS ADD CONSTRAINT FK_FACT_OTC_TRANSACTIONS_DIM_DATE FOREIGN KEY ( CLOSING_INSIDE_BID_DATE ) REFERENCES OTC_MARKET_ANALYSIS.DIM_DATE( DATE_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE OTC_MARKET_ANALYSIS.FACT_OTC_TRANSACTIONS ADD CONSTRAINT FK_FACT_OTC_TRANSACTIONS_DIM_DATE_0 FOREIGN KEY ( CLOSING_INSIDE_ASK_DATE ) REFERENCES OTC_MARKET_ANALYSIS.DIM_DATE( DATE_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE OTC_MARKET_ANALYSIS.FACT_OTC_TRANSACTIONS ADD CONSTRAINT FK_FACT_OTC_TRANSACTIONS_DIM_DATE_1 FOREIGN KEY ( PREVIOUS_CLOSE_DATE ) REFERENCES OTC_MARKET_ANALYSIS.DIM_DATE( DATE_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE OTC_MARKET_ANALYSIS.FACT_OTC_TRANSACTIONS ADD CONSTRAINT FK_FACT_OTC_TRANSACTIONS_DIM_DATE_2 FOREIGN KEY ( SHORT_INTEREST_DATE ) REFERENCES OTC_MARKET_ANALYSIS.DIM_DATE( DATE_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE OTC_MARKET_ANALYSIS.FACT_OTC_TRANSACTIONS ADD CONSTRAINT FK_FACT_OTC_TRANSACTIONS_DIM_DATE_3 FOREIGN KEY ( CLOSING_BEST_BID_DATE ) REFERENCES OTC_MARKET_ANALYSIS.DIM_DATE( DATE_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE OTC_MARKET_ANALYSIS.FACT_OTC_TRANSACTIONS ADD CONSTRAINT FK_FACT_OTC_TRANSACTIONS_DIM_DATE_4 FOREIGN KEY ( CLOSING_BEST_ASK_DATE ) REFERENCES OTC_MARKET_ANALYSIS.DIM_DATE( DATE_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE OTC_MARKET_ANALYSIS.FACT_OTC_TRANSACTIONS ADD CONSTRAINT FK_FACT_OTC_TRANSACTIONS_DIM_DATE_5 FOREIGN KEY ( TOTAL_SHARES_OUTSTANDING_DATE ) REFERENCES OTC_MARKET_ANALYSIS.DIM_DATE( DATE_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;
