-- Create tables with documented relationships

CREATE TABLE `mystic-planet-442018-a4.OTC_MARKET_ANALYSIS.DIM_DATE` (
    DATE_ID INT64 NOT NULL, -- Primary Key
    YEAR_NUMBER INT64,
    MONTH_NUMBER INT64,
    QUARTER_NUMBER INT64,
    DAY_NUMBER INT64,
    DAY_NAME STRING,
    MONTH_NAME STRING,
    WEEK_OF_MONTH INT64,
    WEEK_OF_YEAR INT64
);

CREATE TABLE `mystic-planet-442018-a4.OTC_MARKET_ANALYSIS.DIM_GICS` (
    GICS_ID INT64 NOT NULL, -- Primary Key
    SECTOR_CODE INT64,
    SECTOR_NAME STRING,
    INDUSTRY_GROUP_CODE INT64,
    INDUSTRY_GROUP_NAME STRING,
    INDUSTRY_CODE INT64,
    INDUSTRY_NAME STRING,
    SUB_INDUSTRY_CODE INT64,
    SUB_INDUSTRY_NAME STRING
);

CREATE TABLE `mystic-planet-442018-a4.OTC_MARKET_ANALYSIS.DIM_OTC_TIER` (
    OTC_TIER_ID INT64 NOT NULL, -- Primary Key
    OTC_TIER_NAME STRING,
    DAD_PAL_SPONSOR STRING
);

CREATE TABLE `mystic-planet-442018-a4.OTC_MARKET_ANALYSIS.DIM_SECURITY` (
    SECURITY_ID INT64 NOT NULL, -- Primary Key
    COMPANY_ID INT64,
    TRADING_SYMBOL STRING,
    CUSIP_NUMBER STRING,
    SECURITY_NAME STRING,
    SECURITY_TYPE STRING,
    SECURITY_CLASS STRING,
    SECURITY_STATUS STRING,
    FINRA_ISSUER_IDENTIFIER STRING,
    SECURITY_DESCRIPTION STRING,
    COUNTRY STRING,
    STATE STRING,
    COMPANY_NAME STRING
);

CREATE TABLE `mystic-planet-442018-a4.OTC_MARKET_ANALYSIS.DIM_SOURCE` (
    SOURCE_ID INT64 NOT NULL, -- Primary Key
    BEST_BID_SOURCE STRING,
    BEST_ASK_SOURCE STRING
);

CREATE TABLE `mystic-planet-442018-a4.OTC_MARKET_ANALYSIS.DIM_TRADING_VENUE` (
    TRADING_VENUE_ID INT64 NOT NULL, -- Primary Key
    TRADING_VENUE_NAME STRING
);

CREATE TABLE `mystic-planet-442018-a4.OTC_MARKET_ANALYSIS.FACT_OTC_TRANSACTIONS` (
    FACTS_ID INT64 NOT NULL, -- Primary Key
    CLOSING_INSIDE_BID FLOAT64,
    CLOSING_INSIDE_ASK FLOAT64,
    CLOSING_MID_PRICE FLOAT64,
    PRICE_OPEN FLOAT64,
    PRICE_HIGH FLOAT64,
    PRICE_LOW FLOAT64,
    PRICE_LAST FLOAT64,
    PREVIOUS_CLOSE_PRICE FLOAT64,
    SHARE_VOLUME INT64,
    DOLLAR_VOLUME FLOAT64,
    TRADE_COUNT INT64,
    OTC_LINK_SHARE_VOLUME INT64,
    OTC_LINK_DOLLAR_VOLUME FLOAT64,
    OTC_LINK_TRADE_COUNT INT64,
    REG_SHO_STATUS_FLAG STRING,
    RULE_3210_STATUS_FLAG STRING,
    SHORT_INTEREST_SHARES INT64,
    NUMBER_OF_MARKET_MAKERS INT64,
    BONA_FIDE_CONTINOUS INT64,
    CLOSING_BEST_BID FLOAT64,
    CLOSING_BEST_ASK FLOAT64,
    TOTAL_SHARES_OUTSTANDING FLOAT64,
    CLOSING_SPREAD_INSIDE FLOAT64,
    CLOSING_SPREAD_BEST FLOAT64,
    PIVOT_POINT FLOAT64,
    CAVEAT_EMPTOR_FLAG STRING,
    TRADING_VENUE_ID INT64, -- Foreign Key to DIM_TRADING_VENUE(TRADING_VENUE_ID)
    SOURCE_ID INT64, -- Foreign Key to DIM_SOURCE(SOURCE_ID)
    OTC_TIER_ID INT64, -- Foreign Key to DIM_OTC_TIER(OTC_TIER_ID)
    SECURITY_ID INT64, -- Foreign Key to DIM_SECURITY(SECURITY_ID)
    GICS_ID INT64, -- Foreign Key to DIM_GICS(GICS_ID)
    CLOSING_INSIDE_BID_PRICE_DATE_ID DATE, -- Foreign Key to DIM_DATE(DATE_ID)
    CLOSING_INSIDE_ASK_PRICE_DATE_ID DATE, -- Foreign Key to DIM_DATE(DATE_ID)
    PREVIOUS_CLOSE_DATE_ID DATE, -- Foreign Key to DIM_DATE(DATE_ID)
    SHORT_INTEREST_DATE DATE, -- Foreign Key to DIM_DATE(DATE_ID)
    CLOSING_BEST_BID_DATE_ID DATE, -- Foreign Key to DIM_DATE(DATE_ID)
    CLOSING_BEST_ASK_DATE_ID DATE, -- Foreign Key to DIM_DATE(DATE_ID)
    TOTAL_SHARES_OUTSTANDING_DATE DATE -- Foreign Key to DIM_DATE(DATE_ID)
);

-- Note: Documented relationships can be enforced programmatically in ETL processes or queries.
